/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    ComponentsInDepthInto: typeof import('./src/views/ComponentsInDepthView/components/ComponentsInDepthInto.vue')['default']
    ComponentsInDepthView: typeof import('./src/views/ComponentsInDepthView/ComponentsInDepthView.vue')['default']
    ComponentVModel: typeof import('./src/views/ComponentsInDepthView/components/ComponentVModel.vue')['default']
    HomeView: typeof import('./src/views/HomeView/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotsCommuncation: typeof import('./src/views/ComponentsInDepthView/components/SlotsCommuncation.vue')['default']
    SlotsX: typeof import('./src/views/ComponentsInDepthView/components/SlotsX.vue')['default']
  }
}
