/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    BeyondBasicsWithSlots: typeof import('./src/views/components-in-depth-view/components/BeyondBasicsWithSlots.vue')['default']
    ComponentsInDepthView: typeof import('./src/views/components-in-depth-view/ComponentsInDepthView.vue')['default']
    ComponentVModel: typeof import('./src/views/components-in-depth-view/components/ComponentVModel.vue')['default']
    ContentSection: typeof import('./src/components/ContentSection.vue')['default']
    HomeView: typeof import('./src/views/home-view/HomeView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackedContent: typeof import('./src/components/StackedContent.vue')['default']
  }
}
